<?php

use App\Http\Controllers\Api\Agile\AgileDashboardController;
use App\Http\Controllers\Api\Agile\BugController;
use App\Http\Controllers\Api\Agile\EpicController;
use App\Http\Controllers\Api\Agile\LabelController;
use App\Http\Controllers\Api\Agile\ProjectController;
use App\Http\Controllers\Api\Agile\SprintController;
use App\Http\Controllers\Api\Agile\SquadController;
use App\Http\Controllers\Api\Agile\StoryController;

Route::get('/squads', [SquadController::class, 'index']);
Route::post('/squads', [SquadController::class, 'store']);
Route::put('/squads/{squad}', [SquadController::class, 'update']);
Route::post('/squads/{squad}/members', [SquadController::class, 'addMember']);
Route::delete('/squads/{squad}/members/{userId}', [SquadController::class, 'removeMember']);
Route::get('/sprints', [SprintController::class, 'index']);
Route::post('/sprints', [SprintController::class, 'store']);
Route::put('/sprints/{sprint}', [SprintController::class, 'update']);
Route::post('/sprints/{sprint}/activate', [SprintController::class, 'activate']);
Route::post('/sprints/{sprint}/review', [SprintController::class, 'review']);
Route::post('/sprints/{sprint}/reopen', [SprintController::class, 'reopen']);
Route::post('/sprints/{sprint}/close', [SprintController::class, 'close']);
Route::get('/sprints/{sprint}/board', [SprintController::class, 'board']);
Route::get('/sprints/{sprint}/burndown', [SprintController::class, 'burndown']);
Route::get('/sprints/{sprint}/capacity', [SprintController::class, 'capacity']);
Route::get('/sprints/{sprint}/wip-status', [SprintController::class, 'wipStatus']);
Route::get('/sprints/{sprint}/export', [SprintController::class, 'export']);
Route::get('/epics', [EpicController::class, 'index']);
Route::post('/epics', [EpicController::class, 'store']);
Route::get('/epics/{epic}', [EpicController::class, 'show']);
Route::put('/epics/{epic}', [EpicController::class, 'update']);
Route::delete('/epics/{epic}', [EpicController::class, 'destroy']);
Route::get('/stories', [StoryController::class, 'index']);
Route::post('/stories', [StoryController::class, 'store']);
Route::get('/stories/{story}', [StoryController::class, 'show']);
Route::put('/stories/{story}', [StoryController::class, 'update']);
Route::delete('/stories/{story}', [StoryController::class, 'destroy']);
Route::patch('/stories/{story}/move', [StoryController::class, 'move']);
Route::post('/stories/bulk-move', [StoryController::class, 'bulkMove']);
Route::get('/bugs', [BugController::class, 'index']);
Route::post('/bugs', [BugController::class, 'store']);
Route::post('/bugs/check-duplicates', [BugController::class, 'checkDuplicates']);
Route::post('/bugs/detect-duplicates', [BugController::class, 'detectDuplicates']);
Route::put('/bugs/{bug}', [BugController::class, 'update']);
Route::delete('/bugs/{bug}', [BugController::class, 'destroy']);
Route::patch('/bugs/{bug}/move', [BugController::class, 'move']);
Route::delete('/bugs/{bug}/attachments/{attachmentId}', [BugController::class, 'destroyAttachment']);
Route::get('/agile/dashboard', [AgileDashboardController::class, 'dashboard']);
Route::get('/agile/velocity', [AgileDashboardController::class, 'velocity']);
Route::get('/projects', [ProjectController::class, 'index']);
Route::post('/projects', [ProjectController::class, 'store']);
Route::put('/projects/{project}', [ProjectController::class, 'update']);
Route::delete('/projects/{project}', [ProjectController::class, 'destroy']);
Route::get('/labels', [LabelController::class, 'index']);
Route::post('/labels', [LabelController::class, 'store']);
Route::delete('/labels/{label}', [LabelController::class, 'destroy']);
