<?php

// Auto-generated by database/data/parse-kpis-html.php from public/kpis.html (do not hand-edit).
// KPI scorecards seeded into kpi_scorecard_items by KpiScorecardSeeder.
// Shape: [users.id => [ [name, description, target|null, weight], ... ]].
return [
    5 => [ // Sneha Sunoj
        ['name' => 'Monthly Revenue Growth', 'description' => 'Hima MoM revenue growth from current ₹6 Cr baseline', 'target' => '₹7.5 Cr', 'weight' => 35],
        ['name' => 'Call Connection Rate', 'description' => '% of call attempts that connect AND complete (not dropped)', 'target' => '45%', 'weight' => 25],
        ['name' => 'Day 7 User Retention', 'description' => '% of new users active on day 7 after install', 'target' => '2%', 'weight' => 20],
        ['name' => 'Creator Retention (Monthly Active)', 'description' => '% of creators active in the current month vs last', 'target' => '75%', 'weight' => 20],
    ],
    3 => [ // Nandha
        ['name' => 'CAC (Cost per Paid User)', 'description' => 'Ad spend ÷ paying users acquired · what it actually costs to get a payer', 'target' => '₹450', 'weight' => 30],
        ['name' => 'ROAS (30-day Return on Ad Spend)', 'description' => 'Revenue from acquired users ÷ ad spend, 30-day window', 'target' => '3x', 'weight' => 25],
        ['name' => 'Monthly Install Volume', 'description' => 'Total new installs driven by paid ads', 'target' => '40% MoM', 'weight' => 25],
        ['name' => 'Register → First Purchase Conversion', 'description' => '% of registered users that buy coins within 7 days', 'target' => '28%', 'weight' => 20],
    ],
    11 => [ // Anirudh
        ['name' => 'CAC (Cost per Paid User)', 'description' => 'Ad spend ÷ paying users acquired · what it actually costs to get a payer', 'target' => '₹450', 'weight' => 30],
        ['name' => 'ROAS (30-day Return on Ad Spend)', 'description' => 'Revenue from acquired users ÷ ad spend, 30-day window', 'target' => '3x', 'weight' => 25],
        ['name' => 'Monthly Install Volume', 'description' => 'Total new installs driven by paid ads', 'target' => '40% MoM', 'weight' => 25],
        ['name' => 'Register → First Purchase Conversion', 'description' => '% of registered users that buy coins within 7 days', 'target' => '28%', 'weight' => 20],
    ],
    20 => [ // Krishnan
        ['name' => 'Ad Creatives Shipped Monthly', 'description' => 'AI-generated videos + scripts + graphics handed to ads team', 'target' => '140', 'weight' => 25],
        ['name' => 'Average Ad CTR (Meta + Google)', 'description' => 'Click-through rate across all his creatives in paid ads', 'target' => '2.5%', 'weight' => 25],
        ['name' => 'Ad → Install Conversion', 'description' => '% of ad clicks that convert to app installs', 'target' => '40%', 'weight' => 25],
        ['name' => 'Hit Rate (Ads with CTR > 3%)', 'description' => '% of shipped ads that performed above CTR benchmark', 'target' => '9.5%', 'weight' => 25],
    ],
    17 => [ // Anindita
        ['name' => 'N. India Revenue Growth (MoM)', 'description' => 'Hima MoM revenue growth from North India users', 'target' => '20%', 'weight' => 35],
        ['name' => 'N. India Call Connection Rate', 'description' => '% of call attempts from NI users that connect AND complete', 'target' => '30%', 'weight' => 25],
        ['name' => 'N. India Day 7 User Retention', 'description' => '% of new NI users active on day 7 after install', 'target' => '1%', 'weight' => 20],
        ['name' => 'N. India Creator Retention (Monthly Active)', 'description' => '% of NI creators active in the current month vs last', 'target' => '80%', 'weight' => 20],
    ],
    34 => [ // Yuvanesh
        ['name' => 'Sprint Release Compliance', 'description' => 'Bi-weekly sprints · 2 per month · both ship on planned date', 'target' => '2 / 2', 'weight' => 31],
        ['name' => 'Critical Bugs in Production (P0/P1)', 'description' => 'Critical user-impacting bugs per month — includes security incidents, payment failures, data leaks, fraud exploits', 'target' => '0', 'weight' => 27],
        ['name' => 'Crash-Free Session Rate', 'description' => '% of sessions without app crash', 'target' => '95%', 'weight' => 23],
        ['name' => 'App Store Rating', 'description' => 'Play Store, maintained or trending up', 'target' => '4.5 ★', 'weight' => 19],
    ],
    35 => [ // Rishabh
        ['name' => 'Sprint Release Compliance', 'description' => 'Bi-weekly sprints · 2 per month · both ship on planned date', 'target' => '2 / 2', 'weight' => 32],
        ['name' => 'Critical Bugs in Production (P0/P1)', 'description' => 'Critical user-impacting bugs — includes security, payment, fraud', 'target' => '0', 'weight' => 26],
        ['name' => 'Crash-Free Session Rate', 'description' => '% of sessions without app crash', 'target' => '95%', 'weight' => 22],
        ['name' => 'App Store Rating', 'description' => 'Play Store rating, maintained or trending up', 'target' => '4.5 ★', 'weight' => 20],
    ],
    37 => [ // Perumal
        ['name' => 'Sprint Release Compliance', 'description' => 'Bi-weekly sprints · 2 per month · both ship on planned Friday', 'target' => '2 / 2', 'weight' => 32],
        ['name' => 'Critical Bugs in Production (P0/P1)', 'description' => 'Critical user-impacting bugs per month — includes security, payment, fraud', 'target' => '0', 'weight' => 26],
        ['name' => 'Crash-Free Session Rate', 'description' => '% of sessions without app crash', 'target' => '95%', 'weight' => 22],
        ['name' => 'App Store Rating', 'description' => 'Play Store rating, maintained or trending up', 'target' => '4.5 ★', 'weight' => 20],
    ],
    38 => [ // Maari
        ['name' => 'Sprint Release Compliance', 'description' => 'Bi-weekly sprints · 2 per month · both ship on planned date', 'target' => '2 / 2', 'weight' => 32],
        ['name' => 'Critical Bugs in Production (P0/P1)', 'description' => 'Critical user-impacting bugs per month — includes security, payment, fraud', 'target' => '0', 'weight' => 26],
        ['name' => 'Crash-Free Session Rate', 'description' => '% of sessions without app crash', 'target' => '95%', 'weight' => 22],
        ['name' => 'App Store Rating', 'description' => 'Only Care Play Store rating, maintained or trending up', 'target' => '4.5 ★', 'weight' => 20],
    ],
    2 => [ // Bala
        ['name' => 'Monthly Revenue Growth (Only Care)', 'description' => 'Only Care MoM revenue growth', 'target' => 'TBD', 'weight' => 35],
        ['name' => 'Call Connection Rate (Only Care)', 'description' => '% of call attempts that connect AND complete (not dropped)', 'target' => 'TBD', 'weight' => 25],
        ['name' => 'Day 7 User Retention (Only Care)', 'description' => '% of new users active on day 7 after install', 'target' => 'TBD', 'weight' => 20],
        ['name' => 'Provider/Creator Retention (Monthly Active)', 'description' => '% of providers/creators active in the current month vs last', 'target' => 'TBD', 'weight' => 20],
    ],
    13 => [ // Dhanush
        ['name' => 'Monthly Revenue / User Growth (BLR Connect)', 'description' => 'BLR Connect MoM revenue / active-user growth (Bangalore market)', 'target' => 'TBD', 'weight' => 35],
        ['name' => 'Call Connection Rate (BLR Connect)', 'description' => '% of call attempts that connect AND complete (not dropped)', 'target' => 'TBD', 'weight' => 25],
        ['name' => 'Day 7 User Retention (BLR Connect)', 'description' => '% of new users active on day 7 after install', 'target' => 'TBD', 'weight' => 20],
        ['name' => 'Provider/Creator Retention (Monthly Active)', 'description' => '% of providers/creators active in the current month vs last', 'target' => 'TBD', 'weight' => 20],
    ],
    27 => [ // Ranjini
        ['name' => 'Defect Escape Rate', 'description' => '% of critical bugs that reached prod despite QA', 'target' => '0', 'weight' => 41],
        ['name' => 'Test Coverage (Critical Paths)', 'description' => '% of payment, call, auth flows with automated tests', 'target' => '80%', 'weight' => 32],
        ['name' => 'Bug Verification Turnaround', 'description' => 'Avg time to verify a dev\'s bug fix', 'target' => '≤ 2 days', 'weight' => 27],
    ],
    12 => [ // Tamil Arasan
        ['name' => 'Designs Shipped Monthly', 'description' => 'Figma-final screens/flows handed to dev each month', 'target' => '20', 'weight' => 40],
        ['name' => 'First-Pass Approval Rate', 'description' => '% of designs approved by PM without major revisions', 'target' => '60%', 'weight' => 35],
        ['name' => 'Design System Adoption', 'description' => '% of new features using shared design system components', 'target' => '90%', 'weight' => 25],
    ],
    25 => [ // Deeksha
        ['name' => 'Ticket Resolution Rate', 'description' => '% of tickets resolved by support without escalating to dev/JP', 'target' => '90%', 'weight' => 30],
        ['name' => 'First Response Time (FRT)', 'description' => '% of tickets receiving first response within SLA time', 'target' => '80%', 'weight' => 25],
        ['name' => 'Ticket Re-open Rate', 'description' => '% of resolved tickets reopened by the same user · proxy for satisfaction · no customer rating system in Hima', 'target' => '≤ 5%', 'weight' => 25],
        ['name' => 'Average Resolution Time', 'description' => '% of tickets resolved within SLA time window', 'target' => '100%', 'weight' => 20],
    ],
    51 => [ // Kishore Prabakaran
        ['name' => 'Hima Ad Creatives Shipped Monthly', 'description' => 'Hima-specific AI videos + scripts + graphics handed to ads team', 'target' => '130', 'weight' => 25],
        ['name' => 'Hima Ad CTR (Meta + Google)', 'description' => 'Click-through rate of Hima creatives in paid ads', 'target' => '2%', 'weight' => 25],
        ['name' => 'Hima Ad → Install Conversion', 'description' => '% of Hima ad clicks that convert to app installs', 'target' => '35%', 'weight' => 25],
        ['name' => 'Hima Hit Rate (Ads with CTR > 3%)', 'description' => '% of Hima shipped ads that performed above CTR benchmark', 'target' => '9%', 'weight' => 25],
    ],
    18 => [ // Anaz
        ['name' => 'Videos Edited Per Month', 'description' => 'Final edited videos shipped to ads team', 'target' => '130', 'weight' => 35],
        ['name' => 'Edit Cycle Time', 'description' => 'Avg hours from script/raw footage to final video', 'target' => '≤ 2 days', 'weight' => 25],
        ['name' => 'First-Pass Approval Rate', 'description' => '% of edits Krishnan approves without revision', 'target' => '50%', 'weight' => 25],
        ['name' => 'Output Coverage Across Products', 'description' => 'Hima / Only Care / Unman split matches demand', 'target' => null, 'weight' => 15],
    ],
    57 => [ // Gargi Bisht
        ['name' => 'Organic Follower Growth (MoM)', 'description' => 'Net new followers across all platforms, without paid push', 'target' => '60%', 'weight' => 35],
        ['name' => 'Avg Engagement Rate per Post', 'description' => '(Likes + comments + shares + saves) / views', 'target' => '3%', 'weight' => 30],
        ['name' => 'Posts Per Week (multi-platform)', 'description' => 'Consistent posting cadence across all platforms', 'target' => '20', 'weight' => 20],
        ['name' => 'Reach / Impressions Growth (MoM)', 'description' => 'Total people seeing Hima content organically', 'target' => '20%', 'weight' => 15],
    ],
    55 => [ // Swapna M
        ['name' => 'CAC (Cost per Paid User)', 'description' => 'Ad spend ÷ paying users acquired across non-Hima apps', 'target' => '₹450', 'weight' => 30],
        ['name' => 'ROAS (30-day Return on Ad Spend)', 'description' => 'Revenue from acquired users ÷ ad spend, 30-day window', 'target' => '3x', 'weight' => 25],
        ['name' => 'Monthly Install Volume', 'description' => 'Total new installs from paid ads', 'target' => '40% MoM', 'weight' => 25],
        ['name' => 'Register → First Purchase Conversion', 'description' => '% of registered users that buy coins within 7 days', 'target' => '28%', 'weight' => 20],
    ],
    58 => [ // Sivaranjani N
        ['name' => 'Only Care Ad Creatives Shipped Monthly', 'description' => 'Only Care AI videos + scripts + graphics handed to ads team', 'target' => null, 'weight' => 25],
        ['name' => 'Only Care Ad CTR (Meta + Google)', 'description' => 'Click-through rate of Only Care creatives in paid ads', 'target' => null, 'weight' => 25],
        ['name' => 'Only Care Ad → Install Conversion', 'description' => '% of Only Care ad clicks that convert to app installs', 'target' => null, 'weight' => 25],
        ['name' => 'Only Care Hit Rate (Ads with CTR > 3%)', 'description' => '% of Only Care shipped ads that performed above CTR benchmark', 'target' => null, 'weight' => 25],
    ],
    44 => [ // Saran
        ['name' => 'Self-Serve Dashboard / MCP Coverage', 'description' => '% of standard business questions answerable via dashboards or MCP tools without asking Saran directly', 'target' => '75%', 'weight' => 30],
        ['name' => 'Anomaly Detection Speed', 'description' => 'Time to flag revenue/CAC/retention anomalies after they occur', 'target' => '≤ 4 hrs', 'weight' => 25],
        ['name' => 'Strategic Deep-Dives Delivered', 'description' => 'Major investigations per month (LTV by region, top-creator analysis, payment funnel, etc.)', 'target' => '2 / month', 'weight' => 25],
        ['name' => 'A/B Test Throughput', 'description' => 'A/B tests designed + analyzed per month (with statistical rigor)', 'target' => '2 / month', 'weight' => 20],
    ],
    45 => [ // Meghana
        ['name' => 'Business Recommendations Delivered (monthly)', 'description' => 'Action proposals to Sneha/JP — not findings, but what to DO', 'target' => '6', 'weight' => 30],
        ['name' => 'Recommendation Adoption Rate', 'description' => '% of her recommendations Sneha actually acted on', 'target' => '60%', 'weight' => 30],
        ['name' => 'Decision Memo Turnaround', 'description' => 'Speed when Sneha/JP ask "Should we do X? Build me a case."', 'target' => '≤ 3 days', 'weight' => 20],
        ['name' => 'Weekly Hima Business Report', 'description' => 'Synthesized executive intel for Sneha + JP (not raw data — Saran\'s job)', 'target' => '4 / 4', 'weight' => 20],
    ],
    19 => [ // Sooraj
        ['name' => 'Graphics Designed Per Month', 'description' => 'Final graphic assets shipped to ads / marketing', 'target' => '80', 'weight' => 35],
        ['name' => 'Design Cycle Time', 'description' => 'Avg hours from brief to final asset', 'target' => '≤ 2 days', 'weight' => 25],
        ['name' => 'First-Pass Approval Rate', 'description' => '% of designs Krishnan approves without revision', 'target' => '60%', 'weight' => 25],
        ['name' => 'Output Coverage Across Products', 'description' => 'Hima / Only Care / Unman split matches demand', 'target' => '20', 'weight' => 15],
    ],
    4 => [ // Ayush
        ['name' => 'New Strategic Connections', 'description' => 'Investors · advisors · domain experts · partners introduced to Innovfix per month', 'target' => '1', 'weight' => 30],
        ['name' => 'Expert / Advisor Meetings Conducted', 'description' => 'Meetings held with investors, advisors, or domain experts per month', 'target' => '1', 'weight' => 25],
        ['name' => 'Investment Events & Conferences Attended', 'description' => 'Startup summits, VC events, industry conferences visited per month', 'target' => '1', 'weight' => 25],
        ['name' => 'Investor / Partner Pipeline Advanced', 'description' => 'Conversations moved to next stage — term sheets, LOIs, partnerships, or formal follow-ups per month', 'target' => '1', 'weight' => 20],
    ],
    32 => [ // Shoyab
        ['name' => 'Creator Payout Accuracy & Timeliness', 'description' => '% of creators paid correct amount on schedule', 'target' => '100%', 'weight' => 30],
        ['name' => 'Tax Filing Compliance (GST + TDS)', 'description' => 'All tax filings completed on/before due date', 'target' => '0 penalties · 0 late', 'weight' => 25],
        ['name' => 'Monthly Books Close Time', 'description' => 'Days from month-end to closed books', 'target' => '≤ 5 days', 'weight' => 25],
        ['name' => 'Daily Bank Reconciliation Cadence', 'description' => 'PhonePe + Cashfree + bank statement reconciled daily', 'target' => '22 / 22 days', 'weight' => 20],
    ],
    42 => [ // Sneha Prathap
        ['name' => 'Sprint Release Compliance', 'description' => 'Bi-weekly sprints · 2 per month · both ship on planned date', 'target' => '2 / 2', 'weight' => 32],
        ['name' => 'Critical Bugs in Production (P0/P1)', 'description' => 'Includes AI model issues — accuracy failures, hallucinations, generation errors', 'target' => '0', 'weight' => 26],
        ['name' => 'Crash-Free Session Rate', 'description' => '% of Unman sessions without app crash', 'target' => '95%', 'weight' => 22],
        ['name' => 'App Store Rating', 'description' => 'Unman Play Store rating, maintained or trending up', 'target' => '4.5 ★', 'weight' => 20],
    ],
    61 => [ // Akshara
        ['name' => 'Time to Hire', 'description' => 'Avg days from job posted to offer accepted', 'target' => '5 days', 'weight' => 30],
        ['name' => 'Employee Retention Rate', 'description' => '% of employees retained over rolling quarter', 'target' => '80%', 'weight' => 30],
        ['name' => 'Employee Satisfaction (eNPS)', 'description' => 'Net Promoter Score — would employees recommend Innovfix?', 'target' => '90%', 'weight' => 20],
        ['name' => 'HR Compliance Score', 'description' => 'PF, ESI, labor law, contracts — all on time, zero penalties', 'target' => '100%', 'weight' => 20],
    ],
    41 => [ // Fida Taneem
        ['name' => 'AI Features Shipped Monthly', 'description' => 'Tessa releases + Finance/HR/Ops AI tools built', 'target' => '6', 'weight' => 30],
        ['name' => 'Internal Tool Adoption Rate', 'description' => '% of employees actively using her tools weekly', 'target' => '95%', 'weight' => 30],
        ['name' => 'Hours Saved Across Company (monthly)', 'description' => 'Estimated manual work hours eliminated by her tools', 'target' => null, 'weight' => 25],
        ['name' => 'System Reliability (Uptime + Bug-free)', 'description' => 'Internal tools uptime + critical bug count', 'target' => '98%', 'weight' => 15],
    ],
];
