<?php
/**
 * Generator for database/data/kpi_scorecards.php.
 *
 * Parses the static reference doc public/kpis.html — for each `.person` block it
 * reads the person name and the first `.matrix-table`, extracting each KPI row's
 * name, description, monthly target and weight (the last/“Total” column), while
 * skipping the Total / "Per Product" subtotal rows.
 *
 * Usage (from repo root):
 *   php database/data/parse-kpis-html.php          # human-readable JSON + summary
 *   php database/data/parse-kpis-html.php php > database/data/kpi_scorecards.php
 *
 * After regenerating, re-run:  php artisan db:seed --class=KpiScorecardSeeder
 */

$html = file_get_contents(__DIR__ . '/../../public/kpis.html');
$doc = new DOMDocument();
libxml_use_internal_errors(true);
$doc->loadHTML('<?xml encoding="utf-8" ?>' . $html);
libxml_clear_errors();
$xp = new DOMXPath($doc);

$txt = fn (?DOMNode $n) => $n ? trim(preg_replace('/\s+/', ' ', $n->textContent)) : '';

$out = [];
foreach ($xp->query("//div[@class='person']") as $person) {
    $name = $txt($xp->query(".//div[@class='person-name']", $person)->item(0));
    $table = $xp->query(".//table[contains(@class,'matrix-table')]", $person)->item(0);
    if (! $name || ! $table) {
        continue;
    }
    $rows = [];
    foreach ($xp->query(".//tbody/tr", $table) as $tr) {
        $tds = $xp->query("./td", $tr);
        if ($tds->length < 2) {
            continue;
        }
        $first = $tds->item(0);
        $divs = $xp->query("./div", $first);
        $kname = $divs->length ? $txt($divs->item(0)) : $txt($first);
        // Skip summary / subtotal rows ("Total", "Subtotal · Per Product", "Per Product").
        if ($kname === '' || preg_match('/^(total|subtotal|per product)\b/i', $kname)) {
            continue;
        }
        $desc = $divs->length > 1 ? $txt($divs->item(1)) : '';
        $target = $txt($tds->item(1));
        if (in_array($target, ['—', '-', ''], true)) {
            $target = null;
        }
        preg_match('/\d+/', $txt($tds->item($tds->length - 1)), $m);
        $weight = isset($m[0]) ? (int) $m[0] : null;
        $rows[] = ['name' => $kname, 'description' => $desc, 'target' => $target, 'weight' => $weight];
    }
    $out[] = ['name' => $name, 'kpis' => $rows];
}

// kpis.html person-name -> users.id (verified against the live roster).
$map = [
    'Sneha Sunoj' => 5, 'Nandha' => 3, 'Anirudh' => 11, 'Krishnan' => 20,
    'Anindita' => 17, 'Yuvanesh' => 34, 'Rishabh' => 35, 'Perumal' => 37,
    'Maari' => 38, 'Bala' => 2, 'Dhanush' => 13, 'Ranjini' => 27,
    'Tamil Arasan' => 12, 'Deeksha' => 25, 'Kishore Prabakaran' => 51,
    'Anaz' => 18, 'Gargi Bisht' => 57, 'Swapna M' => 55, 'Sivaranjani N' => 58,
    'Saran' => 44, 'Meghana' => 45, 'Sooraj' => 19, 'Ayush' => 4,
    'Shoyab' => 32, 'Sneha Prathap' => 42, 'Akshara' => 61, 'Fida Taneem' => 41,
];

if (($argv[1] ?? '') === 'php') {
    $q = fn ($s) => "'" . str_replace("'", "\\'", $s) . "'";
    $lines = ['<?php', '',
        '// Auto-generated by database/data/parse-kpis-html.php from public/kpis.html (do not hand-edit).',
        '// KPI scorecards seeded into kpi_scorecard_items by KpiScorecardSeeder.',
        '// Shape: [users.id => [ [name, description, target|null, weight], ... ]].',
        'return ['];
    foreach ($out as $p) {
        if (! isset($map[$p['name']])) { fwrite(STDERR, "UNMAPPED: {$p['name']}\n"); continue; }
        if (empty($p['kpis'])) { fwrite(STDERR, "NO KPIS: {$p['name']}\n"); continue; }
        $lines[] = "    {$map[$p['name']]} => [ // {$p['name']}";
        foreach ($p['kpis'] as $k) {
            $t = $k['target'] === null ? 'null' : $q($k['target']);
            $w = $k['weight'] === null ? 'null' : $k['weight'];
            $lines[] = "        ['name' => {$q($k['name'])}, 'description' => {$q($k['description'])}, 'target' => {$t}, 'weight' => {$w}],";
        }
        $lines[] = '    ],';
    }
    $lines[] = '];';
    echo implode("\n", $lines) . "\n";
    exit;
}

echo json_encode($out, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n\n=== SUMMARY ===\n";
foreach ($out as $p) {
    $sum = array_sum(array_map(fn ($k) => $k['weight'] ?? 0, $p['kpis']));
    echo str_pad($p['name'], 24) . ' id=' . ($map[$p['name']] ?? '??') . ' kpis=' . count($p['kpis']) . " weightSum={$sum}\n";
}
